sudo: required
services:
    - docker

before_install:
    - docker build -t 1111222211112222/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true 1111222211112222/frontend npm run test

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-498738601876"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY